name: "Pre-audit pull request"
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main
      - master
    paths:
      - newicons/*
  workflow_dispatch:
    
jobs:
  Audit-SVGs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Check icons drawability
        run: |
          uv run scripts/generate-icons.py --checksrc newicons --checkonly -e

  Audit-Appfilter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Check icons appfilter entries
        run: |
          uv run scripts/check-appfilter.py -c generate-icons.toml -e newicons/appfilter.json 
